from bloom_filter import BloomFilter

b = BloomFilter(max_elements=1000, error_rate=0.5)
b.add('ATGCGGAGTCTGCGTCGCAGACTGCTCGTCGTGCTCGTCGATCACTCACAGACAAGTCGTTGCACAAGCAGCTAC')
b.add('CTAGCTACACTAGCTACTCTATGCTGCATCGATGACGTCAGTCGAGTGCTGACTATCTACTACTGCATGCTAGTG')
b.add('ATGCATGCAGTCGTCGTATCTGACTGATCGATCA CGACTAC ACTCGTA CTAGC CATCTAGC  CATGCA A')
b.add('GATC CTA GCCAT CAGTCGCTAGCTA TACTGCTAGCT TACTACGTCGTC TACTAGC ATCTAGC TCTAC')
b.add('TAGCCGTCGCT CTATGCGATCCTA TGCATCGCTA GCTCTACGCTGCGATCATCTCAGGTCAGTCAGTAC TA')


variant = "ATGCGGAGTCTGCGTCGCAGACTGCCCGTCGTGCTCGTCGATCACTCACAGACAAGTCGTTGCACAAGCAGCTAC"

print(variant in b)

# print(b.)


  

# if __name__ == "__main__":
#   m_key = int(input())
#   k_key = int(input())

#   bf = BloomFilter(m_key, k_key)
#   insertion = str(input())
#   bf.insert(insertion)
#   print(bf.data)

#   print("it works!!")